version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  redis-geo:
    image: redis
    ports:
      - "6381:6379"

  redis-pop:
    image: redis
    ports:
      - "6380:6379"

  backend:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis-geo
      - redis-pop
    environment:
    - REDIS_GEO_HOST=redis-geo
    - REDIS_GEO_PORT=6379
    - REDIS_POP_HOST=redis-pop
    - REDIS_POP_PORT=6379
    - MONGO_URI=mongodb://mongo:27017


  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "9000:9000"
    depends_on:
      - backend
